# Your name and what you do
name: Otino Pio Santosuosso
bio: Computer science student

description: Otino Pio Santosuosso's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://Pio57.github.io/MyPortfolio/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: mytwitter
linkedin: /otino-pio-santosuosso-780375229
github: /Pio57
email: Pio57_2015@libero.it
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - HTML
    - CSS
    - Javascript
    - Java, Android
    - Python
    - MySQL
    - Git

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    UniNotes:
        name: UniNotes
        description: Un Website che offre agli studenti universitari la possibilità di scambiare materiale didattico e avere un resoconto dei propri esami sostenuti.
        url: https://github.com/Pio57/UniNotes
    UniNotesFIA:
        name: UniNotesFIA
        description: Un modulo di intelligenza artificiale scritto in Python che suggerirà ad uno studente di informatica una possile magistrale in base alle caratteristiche dello studente.
        url: https://github.com/AlessandraParziale/UniNotesFIA

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
